gestion_projet:
    resource: "@GestionProjetBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /

article:
    resource: "@GestionProjetBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article
    
produit:
    resource: "@GestionProjetBundle/Resources/config/routing/produit.yml"
    prefix:   /produit    

devis:
    resource: "@GestionProjetBundle/Resources/config/routing/devi.yml"
    prefix:   /devi 
    
   

    
