devi_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Devi:index" }
    methods:  GET

devi_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Devi:show" }
    methods:  GET

devi_new:
    path:     /{_locale}/new
    defaults: { _controller: "GestionProjetBundle:Devi:new" }
    methods:  [GET, POST]
    requirements:
        _locale: en|fr # les locales disponibles, séparées par des pipes « | »

devi_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Devi:edit" }
    methods:  [GET, POST]

devi_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Devi:delete" }
    methods:  DELETE

devi_modifier:
    path:     /modifier
    defaults: { _controller: "GestionProjetBundle:Devi:modifier" }