<?php

namespace myapp\GestionProjetBundle\Repository;

/**
 * DeviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviRepository extends \Doctrine\ORM\EntityRepository
{
}
